// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SFB.Infrastructure.Contexts;

#nullable disable

namespace SFB.Infrastructure.Migrations
{
    [DbContext(typeof(SFBContext))]
    [Migration("20251019163855_InvTxn")]
    partial class InvTxn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SFB.Infrastructure.Entities.AMS.EPerson", b =>
                {
                    b.Property<int>("NroPerson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NroPerson"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstLastName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("SecondLastName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("NroPerson");

                    b.ToTable("AMS_Person", (string)null);
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.AMS.ETypePerson", b =>
                {
                    b.Property<int>("NroPerson")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("NroPerson", "Type");

                    b.ToTable("AMS_TypePerson", (string)null);
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.AMS.EUser", b =>
                {
                    b.Property<string>("NameUser")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("NroPerson")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("NameUser");

                    b.HasIndex("NroPerson");

                    b.ToTable("AMS_User", (string)null);
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.AMS.EUserGroup", b =>
                {
                    b.Property<string>("NameUser")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("NroGroup")
                        .HasColumnType("integer");

                    b.HasKey("NameUser", "NroGroup");

                    b.HasIndex("NroGroup");

                    b.ToTable("AMS_UserGroup", (string)null);
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.CMS.EGroup", b =>
                {
                    b.Property<int>("NroGroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NroGroup"));

                    b.Property<string>("CodModule")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("NroGroup");

                    b.HasIndex("CodModule");

                    b.ToTable("CMS_Group", (string)null);
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.CMS.EGroupOption", b =>
                {
                    b.Property<int>("NroGroup")
                        .HasColumnType("integer");

                    b.Property<string>("CodOption")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("NroGroup", "CodOption");

                    b.HasIndex("CodOption");

                    b.ToTable("CMS_GroupOption", (string)null);
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.CMS.EModule", b =>
                {
                    b.Property<string>("CodModule")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("CodModule");

                    b.ToTable("CMS_Module", (string)null);
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.CMS.EOptionMenu", b =>
                {
                    b.Property<string>("CodOption")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CodGruOption")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Route")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CodOption");

                    b.HasIndex("CodGruOption");

                    b.ToTable("CMS_OptionMenu", (string)null);
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.IAW.EInvDetail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetailId"));

                    b.Property<int>("NroProduct")
                        .HasColumnType("integer");

                    b.Property<decimal>("QtyProduct")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TxnId")
                        .HasColumnType("integer");

                    b.HasKey("DetailId");

                    b.HasIndex("NroProduct");

                    b.HasIndex("TxnId");

                    b.ToTable("IAW_InvDetail", (string)null);
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.IAW.EInventoryTxn", b =>
                {
                    b.Property<int>("TxnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TxnId"));

                    b.Property<DateTime>("DateReg")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateUpd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Delete")
                        .HasColumnType("boolean");

                    b.Property<string>("ModOrigin")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int?>("TxnOrigin")
                        .HasColumnType("integer");

                    b.Property<string>("UserReg")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserUpd")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("WareHouseDest")
                        .HasColumnType("integer");

                    b.Property<int?>("WarehouseOri")
                        .HasColumnType("integer");

                    b.HasKey("TxnId");

                    b.HasIndex("WareHouseDest");

                    b.HasIndex("WarehouseOri");

                    b.ToTable("IAW_InventoryTxn", (string)null);
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.IAW.EProduct", b =>
                {
                    b.Property<int>("NroProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NroProduct"));

                    b.Property<DateTime>("DateReg")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateUpd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPurchases")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSales")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<string>("UserReg")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserUpd")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("NroProduct");

                    b.ToTable("IAW_Product", (string)null);
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.IAW.EStock", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StockId"));

                    b.Property<DateTime>("DateReg")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateUpd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NroProduct")
                        .HasColumnType("integer");

                    b.Property<decimal>("QtyOnHand")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("QtyReserved")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ReorderPoint")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("UserReg")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserUpd")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer");

                    b.HasKey("StockId");

                    b.HasIndex("NroProduct");

                    b.HasIndex("WarehouseId");

                    b.ToTable("IAW_Stock");
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.IAW.EWarehouse", b =>
                {
                    b.Property<int>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WarehouseId"));

                    b.Property<DateTime>("DateReg")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateUpd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<string>("UserReg")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserUpd")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("WarehouseId");

                    b.ToTable("IAW_Warehouse", (string)null);
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.AMS.EUser", b =>
                {
                    b.HasOne("SFB.Infrastructure.Entities.AMS.EPerson", "Person")
                        .WithMany("Users")
                        .HasForeignKey("NroPerson")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.AMS.EUserGroup", b =>
                {
                    b.HasOne("SFB.Infrastructure.Entities.AMS.EUser", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("NameUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SFB.Infrastructure.Entities.CMS.EGroup", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("NroGroup")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.CMS.EGroup", b =>
                {
                    b.HasOne("SFB.Infrastructure.Entities.CMS.EModule", "Module")
                        .WithMany("Groups")
                        .HasForeignKey("CodModule")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.CMS.EGroupOption", b =>
                {
                    b.HasOne("SFB.Infrastructure.Entities.CMS.EOptionMenu", "OptionMenu")
                        .WithMany("GroupOptions")
                        .HasForeignKey("CodOption")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SFB.Infrastructure.Entities.CMS.EGroup", "Group")
                        .WithMany("GroupOptions")
                        .HasForeignKey("NroGroup")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("OptionMenu");
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.CMS.EOptionMenu", b =>
                {
                    b.HasOne("SFB.Infrastructure.Entities.CMS.EOptionMenu", "OptionMenu")
                        .WithMany("OptionMenus")
                        .HasForeignKey("CodGruOption")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OptionMenu");
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.IAW.EInvDetail", b =>
                {
                    b.HasOne("SFB.Infrastructure.Entities.IAW.EProduct", "Product")
                        .WithMany("InvDetails")
                        .HasForeignKey("NroProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SFB.Infrastructure.Entities.IAW.EInventoryTxn", "InventoryTxn")
                        .WithMany("InvDetails")
                        .HasForeignKey("TxnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryTxn");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.IAW.EInventoryTxn", b =>
                {
                    b.HasOne("SFB.Infrastructure.Entities.IAW.EWarehouse", "WarehouseDest")
                        .WithMany("TxnsAsDestination")
                        .HasForeignKey("WareHouseDest");

                    b.HasOne("SFB.Infrastructure.Entities.IAW.EWarehouse", "WarehouseOrigin")
                        .WithMany("TxnsAsOrigin")
                        .HasForeignKey("WarehouseOri");

                    b.Navigation("WarehouseDest");

                    b.Navigation("WarehouseOrigin");
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.IAW.EStock", b =>
                {
                    b.HasOne("SFB.Infrastructure.Entities.IAW.EProduct", "Product")
                        .WithMany()
                        .HasForeignKey("NroProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SFB.Infrastructure.Entities.IAW.EWarehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.AMS.EPerson", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.AMS.EUser", b =>
                {
                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.CMS.EGroup", b =>
                {
                    b.Navigation("GroupOptions");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.CMS.EModule", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.CMS.EOptionMenu", b =>
                {
                    b.Navigation("GroupOptions");

                    b.Navigation("OptionMenus");
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.IAW.EInventoryTxn", b =>
                {
                    b.Navigation("InvDetails");
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.IAW.EProduct", b =>
                {
                    b.Navigation("InvDetails");
                });

            modelBuilder.Entity("SFB.Infrastructure.Entities.IAW.EWarehouse", b =>
                {
                    b.Navigation("TxnsAsDestination");

                    b.Navigation("TxnsAsOrigin");
                });
#pragma warning restore 612, 618
        }
    }
}
